spring:
  profiles:
    active: test

---
spring:
  profiles: dev
server:
  port: 8081
person1:
  last_name: hello1
  age: 18
  boss: false
  birth: 2017/12/12
  maps: {k1: v1,k2: 12}
  lists:
    - lisi
    - zhaoliu
  dog:
    name: 小狗1
    age: 12

---
spring:
  profiles: test
server:
  port: 8081
person1:
  last_name: hello2
  age: 18
  boss: false
  birth: 2017/12/12
  maps: {k1: v1,k2: 12}
  lists:
    - lisi
    - zhaoliu
  dog:
    name: 小狗1
    age: 12